### ISSUE TITLE
Boot problems

### ISSUE THREAD

**Issue by tommasobenatti** [Zero-zer0/Huawei_Matebook_D_Hackintosh_OpenCore#1]
I finaly made to install MacOS but he didn't recognize the internal usb ports.
Pls help me to fix this BIG problem

**Comment by Zero-zer0** [comment]
There could be some USB map differences between China and overseas version of Matebook D, which could lead to this issue. Now USBports.kext is replaced by USBInjectAll.kext so the problem is probably solved. However, making your own USBports.kext by Hackintool is recommended.
