### ISSUE TITLE
声音小

### ISSUE THREAD

**Issue by lyydhy** [Zero-zer0/Huawei_Matebook_D_Hackintosh_OpenCore#2]
大佬我是matebook d 2018  声音注入21过后还是感觉很小啊声音 有办法吗？

**Comment by Zero-zer0** [comment]
1. 我没有发现类似的问题，这扬声器挺炸的。请检查软件内的音量设置并排除硬件问题。
2. 可以尝试其他声卡ID。layout-id=56时会有杂音，睡眠唤醒后耳机孔会失效。layout-id=57时，除了无法静音外没太大问题。

**Comment by lyydhy** [comment]
硬件这些应该都没问题毕竟我在win和linux下斗是没问题的，我还是就这样用吧 小点就小点 比没得好  谢谢

**Comment by lyydhy** [comment]
我今天试了一下56  57  直接没声音  21  要把声音开到90%以上才感觉很大
